# Generated by Django 3.1.6 on 2021-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_App', '0003_auto_20210217_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30, verbose_name='用户余额'),
        ),
    ]
