# Generated by Django 3.1.6 on 2021-02-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_App', '0004_auto_20210217_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='AnotherId',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='BlankCard',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='CapitalPwd',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='NameCards',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='TrueName',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='balance',
        ),
    ]
