# Generated by Django 3.1.6 on 2021-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_App', '0005_auto_20210217_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='UserName',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
